### ISSUE TITLE
Bingiemod Video Info Dialog Movie/Show and Cast meta error

### ISSUE THREAD

**Issue by minhgi** [henryjfry/repository.thenewdiamond#1]
In BingieMod, when I click on Dialog Movie/Show and Cast, extendedinfo would give me these error. Looks like it's passing on the wrong inquiry.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/jw4VFhZ/2021-09-15-093006.png" alt="2021-09-15-093006" border="0"></a>

<a href="https://ibb.co/xsyszvK"><img src="https://i.ibb.co/DbNbwXP/2021-09-15-094557.png" alt="2021-09-15-094557" border="0"></a>

2021-09-15 09:20:05.308 T:18800   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 466, in start_info_actions
                                                       wm.open_movie_info(movie_id=params.get('id'), dbid=params.get('dbid'), imdb_id=params.get('imdb_id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 64, in open_movie_info
                                                       self.open_dialog(dialog, prev_window)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 263, in open_dialog
                                                       self.last_control = xbmc.getInfoLabel('System.CurrentControlId').decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-09-15 09:20:05.715 T:18800    INFO <general>: Python interpreter stopped
2021-09-15 09:20:06.211 T:19564    INFO <general>: SEREN (75): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:06.299 T:19564 WARNING <general>: SEREN (75): We received no titles to build a list
2021-09-15 09:20:06.302 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:06.309 T:19564    INFO <general>: CPythonInvoker(116, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:06.320 T:16220    INFO <general>: initializing python engine.
2021-09-15 09:20:06.709 T:19564    INFO <general>: Python interpreter stopped
2021-09-15 09:20:07.087 T:16220    INFO <general>: plugin.program.autowidget: [ mode: path ][ action: cycling ][ group: seren-1631372012.845408 ][ id: 69a700f7-c0dd-4039-8aed-7e39b7639d81 ][ refresh: 1631715606.3070972 ]
2021-09-15 09:20:07.122 T:16220    INFO <general>: plugin.program.autowidget: Read cache 179752B (exp:2:59:13, last:0:00:02): 1c5bb ['8b9e559e-7a49-4706-8619-6779662c0b4c', None, '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:07.203 T:16220    INFO <general>: plugin.program.autowidget: Empty cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:07.204 T:16220    INFO <general>: CPythonInvoker(117, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.program.autowidget\main.py): script successfully run
2021-09-15 09:20:07.733 T:15284    INFO <general>: plugin.program.autowidget: Dequeued cache update: 7a8e6
2021-09-15 09:20:07.734 T:8928     INFO <general>: initializing python engine.
2021-09-15 09:20:07.978 T:16220    INFO <general>: Python interpreter stopped
2021-09-15 09:20:08.779 T:8928     INFO <general>: SEREN (77): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:08.863 T:8928  WARNING <general>: SEREN (77): We received no titles to build a list
2021-09-15 09:20:08.864 T:8928     INFO <general>: CPythonInvoker(118, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:09.262 T:8928     INFO <general>: Python interpreter stopped
2021-09-15 09:20:09.264 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:09.286 T:19340    INFO <general>: initializing python engine.
2021-09-15 09:20:09.681 T:19340    INFO <general>: plugin.program.autowidget: [ mode: path ][ action: cycling ][ group: seren-1631372012.845408 ][ id: 69a700f7-c0dd-4039-8aed-7e39b7639d81 ][ refresh: 1631715609.2692404 ]
2021-09-15 09:20:09.711 T:19340    INFO <general>: plugin.program.autowidget: Read cache 179752B (exp:2:59:10, last:0:00:02): 1c5bb ['8b9e559e-7a49-4706-8619-6779662c0b4c', None, '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:09.769 T:19340    INFO <general>: plugin.program.autowidget: Empty cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:09.770 T:19340    INFO <general>: CPythonInvoker(119, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.program.autowidget\main.py): script successfully run
2021-09-15 09:20:10.284 T:15284    INFO <general>: plugin.program.autowidget: Dequeued cache update: 7a8e6
2021-09-15 09:20:10.285 T:19592    INFO <general>: initializing python engine.
2021-09-15 09:20:10.549 T:19340    INFO <general>: Python interpreter stopped
2021-09-15 09:20:11.396 T:19592    INFO <general>: SEREN (79): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:11.479 T:19592 WARNING <general>: SEREN (79): We received no titles to build a list
2021-09-15 09:20:11.480 T:19592    INFO <general>: CPythonInvoker(120, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:11.908 T:19592    INFO <general>: Python interpreter stopped
2021-09-15 09:20:11.909 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:11.923 T:14016    INFO <general>: initializing python engine.
2021-09-15 09:20:12.327 T:14016    INFO <general>: plugin.program.autowidget: [ mode: path ][ action: cycling ][ group: seren-1631372012.845408 ][ id: 69a700f7-c0dd-4039-8aed-7e39b7639d81 ][ refresh: 1631715611.9141853 ]
2021-09-15 09:20:12.359 T:14016    INFO <general>: plugin.program.autowidget: Read cache 179752B (exp:2:59:08, last:0:00:02): 1c5bb ['8b9e559e-7a49-4706-8619-6779662c0b4c', None, '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:12.387 T:12124    INFO <general>: initializing python engine.
2021-09-15 09:20:12.663 T:14016    INFO <general>: plugin.program.autowidget: Empty cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:12.665 T:14016    INFO <general>: CPythonInvoker(121, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.program.autowidget\main.py): script successfully run
2021-09-15 09:20:12.908 T:14016    INFO <general>: Python interpreter stopped
2021-09-15 09:20:12.923 T:15284    INFO <general>: plugin.program.autowidget: Dequeued cache update: 7a8e6
2021-09-15 09:20:12.924 T:19120    INFO <general>: initializing python engine.
2021-09-15 09:20:13.565 T:12124    INFO <general>: CPythonInvoker(122, C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py): script successfully run
2021-09-15 09:20:13.569 T:1976     INFO <general>: initializing python engine.
2021-09-15 09:20:13.844 T:12124    INFO <general>: Python interpreter stopped
2021-09-15 09:20:14.780 T:19120    INFO <general>: SEREN (82): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:14.967 T:19120 WARNING <general>: SEREN (82): We received no titles to build a list
2021-09-15 09:20:14.970 T:1976    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 472, in start_info_actions
                                                       wm.open_actor_info(actor_id=params.get('id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 189, in open_actor_info
                                                       name = name.decode('utf-8').split(' ' + 'as' + ' ')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-09-15 09:20:14.971 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:15.271 T:14188    INFO <general>: initializing python engine.
2021-09-15 09:20:15.409 T:1976     INFO <general>: Python interpreter stopped
2021-09-15 09:20:15.409 T:19120    INFO <general>: CPythonInvoker(123, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:15.844 T:19120    INFO <general>: Python interpreter stopped
2021-09-15 09:20:16.229 T:14188    INFO <general>: plugin.program.autowidget: [ mode: path ][ action: cycling ][ group: seren-1631372012.845408 ][ id: 69a700f7-c0dd-4039-8aed-7e39b7639d81 ][ refresh: 1631715615.2601564 ]
2021-09-15 09:20:16.264 T:14188    INFO <general>: plugin.program.autowidget: Read cache 179752B (exp:2:59:04, last:0:00:03): 1c5bb ['8b9e559e-7a49-4706-8619-6779662c0b4c', None, '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:16.365 T:14188    INFO <general>: plugin.program.autowidget: Empty cache 0B (exp:-1 day, 23:59:40, last:0:00:03): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:16.366 T:14188    INFO <general>: CPythonInvoker(125, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.program.autowidget\main.py): script successfully run
2021-09-15 09:20:16.854 T:15284    INFO <general>: plugin.program.autowidget: Dequeued cache update: 7a8e6
2021-09-15 09:20:16.856 T:8768     INFO <general>: initializing python engine.
2021-09-15 09:20:17.106 T:14188    INFO <general>: Python interpreter stopped
2021-09-15 09:20:17.917 T:8768     INFO <general>: SEREN (84): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:17.997 T:8768  WARNING <general>: SEREN (84): We received no titles to build a list
2021-09-15 09:20:17.997 T:8768     INFO <general>: CPythonInvoker(126, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:18.393 T:8768     INFO <general>: Python interpreter stopped
2021-09-15 09:20:18.394 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:18.404 T:19012    INFO <general>: initializing python engine.
2021-09-15 09:20:18.763 T:19012    INFO <general>: plugin.program.autowidget: [ mode: path ][ action: cycling ][ group: seren-1631372012.845408 ][ id: 69a700f7-c0dd-4039-8aed-7e39b7639d81 ][ refresh: 1631715618.3982189 ]
2021-09-15 09:20:18.798 T:19012    INFO <general>: plugin.program.autowidget: Read cache 179752B (exp:2:59:01, last:0:00:02): 1c5bb ['8b9e559e-7a49-4706-8619-6779662c0b4c', None, '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:18.999 T:19012    INFO <general>: plugin.program.autowidget: Empty cache 0B (exp:-1 day, 23:59:40, last:0:00:02): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81']
2021-09-15 09:20:19.000 T:19012    INFO <general>: CPythonInvoker(127, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.program.autowidget\main.py): script successfully run
2021-09-15 09:20:19.416 T:15284    INFO <general>: plugin.program.autowidget: Dequeued cache update: 7a8e6
2021-09-15 09:20:19.417 T:10668    INFO <general>: initializing python engine.
2021-09-15 09:20:19.708 T:19012    INFO <general>: Python interpreter stopped
2021-09-15 09:20:20.542 T:10668    INFO <general>: SEREN (86): Seren, Running Path - {'action': 'moviesRecommended', 'from_widget': 'false', 'page': '2'}
2021-09-15 09:20:20.614 T:10668 WARNING <general>: SEREN (86): We received no titles to build a list
2021-09-15 09:20:20.614 T:10668    INFO <general>: CPythonInvoker(128, C:\Users\minhgi\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py): script successfully run
2021-09-15 09:20:20.883 T:15284    INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:0:00:01): 7a8e6 ['8b9e559e-7a49-4706-8619-6779662c0b4c', '69a700f7-c0dd-4039-8aed-7e39b7639d81', None]
2021-09-15 09:20:21.016 T:10668    INFO <general>: Python interpreter stopped
2021-09-15 09:20:21.185 T:15012   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/Hartswood Films.png
2021-09-15 09:20:22.852 T:17272   ERROR <general>: Skipped 1 duplicate messages..
2021-09-15 09:20:22.852 T:17272   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/b/b1f97f11.jpg
2021-09-15 09:20:22.852 T:19608   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/4212f3d8.png
2021-09-15 09:20:22.858 T:15012   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/9/9384b8fa.jpg
2021-09-15 09:20:23.240 T:15012   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/9/968a3e64.jpg
2021-09-15 09:20:25.602 T:15012   ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/a/afdd6bd2.jpg
2021-09-15 09:20:27.093 T:11444    INFO <general>: initializing python engine.
2021-09-15 09:20:28.352 T:11444    INFO <general>: CPythonInvoker(129, C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py): script successfully run
2021-09-15 09:20:28.646 T:11444    INFO <general>: Python interpreter stopped
2021-09-15 09:20:30.518 T:14952    INFO <general>: initializing python engine.
2021-09-15 09:20:32.538 T:14952   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 491, in start_info_actions
                                                       wm.open_tvshow_info(tmdb_id=params.get('id'), tvdb_id=params.get('tvdb_id'), dbid=params.get('dbid'), imdb_id=params.get('imdb_id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 124, in open_tvshow_info
                                                       self.open_dialog(dialog, prev_window)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 263, in open_dialog
                                                       self.last_control = xbmc.getInfoLabel('System.CurrentControlId').decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-09-15 09:20:32.965 T:14952    INFO <general>: Python interpreter stopped
2021-09-15 09:20:35.250 T:1984    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/2893d07c.jpg
2021-09-15 09:20:37.139 T:16508    INFO <general>: initializing python engine.
2021-09-15 09:20:37.863 T:16508    INFO <general>: CPythonInvoker(131, C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py): script successfully run
2021-09-15 09:20:37.871 T:5432     INFO <general>: initializing python engine.
2021-09-15 09:20:38.158 T:16508    INFO <general>: Python interpreter stopped
2021-09-15 09:20:38.888 T:5432    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 472, in start_info_actions
                                                       wm.open_actor_info(actor_id=params.get('id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 189, in open_actor_info
                                                       name = name.decode('utf-8').split(' ' + 'as' + ' ')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

**Comment by henryjfry** [comment]
Very possibly but your log doesnt show the error.  Upload the log file as an attachment

**Comment by henryjfry** [comment]
Ok in WindowManager.py:

Line 263, replace:

self.last_control = xbmc.getInfoLabel('System.CurrentControlId').decode('utf-8')

with 

self.last_control = xbmc.getInfoLabel('System.CurrentControlId')

And also line 189:

replace:

name = name.decode('utf-8').split(' ' + 'as' + ' ')

with

name = name.split(' ' + 'as' + ' ')

**Comment by minhgi** [comment]
Let give it a try

**Comment by minhgi** [comment]
Movies and Show info pull up correctly with the change.  Cast info gave this error when selecting actor or actress.

<a href="https://ibb.co/S7qBsHF"><img src="https://i.ibb.co/dJnDWX8/2021-09-15-100124.png" alt="2021-09-15-100124" border="0"></a>

2021-09-15 09:20:32.538 T:14952   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 491, in start_info_actions
                                                       wm.open_tvshow_info(tmdb_id=params.get('id'), tvdb_id=params.get('tvdb_id'), dbid=params.get('dbid'), imdb_id=params.get('imdb_id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 124, in open_tvshow_info
                                                       self.open_dialog(dialog, prev_window)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 263, in open_dialog
                                                       self.last_control = xbmc.getInfoLabel('System.CurrentControlId').decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-09-15 09:20:32.965 T:14952    INFO <general>: Python interpreter stopped
2021-09-15 09:20:35.250 T:1984    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/2893d07c.jpg
2021-09-15 09:20:37.139 T:16508    INFO <general>: initializing python engine.
2021-09-15 09:20:37.863 T:16508    INFO <general>: CPythonInvoker(131, C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py): script successfully run
2021-09-15 09:20:37.871 T:5432     INFO <general>: initializing python engine.
2021-09-15 09:20:38.158 T:16508    INFO <general>: Python interpreter stopped
2021-09-15 09:20:38.888 T:5432    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 33, in <module>
                                                       Main()
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\script.py", line 12, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\process.py", line 472, in start_info_actions
                                                       wm.open_actor_info(actor_id=params.get('id'), name=params.get('name'))
                                                     File "C:\Users\minhgi\AppData\Roaming\Kodi\addons\script.extendedinfo\resources\lib\WindowManager.py", line 189, in open_actor_info
                                                       name = name.decode('utf-8').split(' ' + 'as' + ' ')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

**Comment by minhgi** [comment]
thanks Henry for your help...got it work out.

**Comment by henryjfry** [comment]
Resolved in the newest version
